version: "3.8"
services:
  prometheus-service-demo-0:
    image: docker.io/julius/prometheus-demo-service:latest
    ports:
      - "10000:8080"
    networks:
      - monitoring

  prometheus-service-demo-1:
    image: docker.io/julius/prometheus-demo-service:latest
    ports:
      - "20000:8080"
    networks:
      - monitoring

  prometheus-service-demo-2:
    image: docker.io/julius/prometheus-demo-service:latest
    ports:
      - "30000:8080"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
    command:
      - "--collector.filesystem"
      - "--collector.filesystem.mount-points-exclude=\"^/(dev|proc|run|sys|media|mnt|var/lib/docker/.+)($|/)\""
    networks:
      - monitoring
  

volumes:
  grafana-storage:

networks:
  monitoring:
    driver: bridge
