{
 "title": "Práctica - punto 4",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Promedio duración solicitudes HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(demo_api_request_duration_seconds_sum[5m])) by (path, method) /\r\nsum(rate(demo_api_request_duration_seconds_count[5m])) by (path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 duración solicitudes HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(demo_api_request_duration_seconds_bucket[5m])) by (le, path, method, status))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 duración solicitudes HTTP",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_api_request_duration_seconds_bucket[5m])) by (le, path, method))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}